### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by egpbos** [NLeSC/software.esciencecenter.nl#29]
In expertises, Accellerated should be Accelerated. When I change this in the schema file, the validator still complains, referencing Accellerated as correct.

**Comment by blootsvoets** [comment]
Unless explicitly told otherwise, `estep validate` will download the schemas from http://software.esciencecenter.nl/, so editing them locally will not change the value. However, you can run `estep validate --schemadir schema` and if the pull request comes through, `estep validate --local`. Does it work with these flags?

**Comment by egpbos** [comment]
Yep, using the `--schemadir` option works. How to proceed, who is authorized to change the schema? Should I just do a pull request?
