### ISSUE TITLE
Test the jekyll templating

### ISSUE THREAD

**Issue by blootsvoets** [NLeSC/software.esciencecenter.nl#75]
Liquid templates also need to be tested. It already failed for a nested object that was not validated by the schema.

**Comment by sverhoeven** [comment]
We could do a `jekyll build` in Travis-CI.

**Comment by sverhoeven** [comment]
Could not get Python and correct Ruby version in docker based Travis CI worker.

Switched to non-docker worker to perform jekyll build in docker container.
This nicely matches the instructions of the README.md.

Sadly today the `jekyll/jekyll:pages` docker image was updated by a broken image.

**Comment by sverhoeven** [comment]
Instead of use a non-container based worker we could also have used container based worker in combination with (apt addon)[https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-on-Container-Based-Infrastructure], 
By using language: python and apt install ruby or the other way around.
This way would have build faster as there are more container based workers and apt is cached, but we choose the jekyll build in docker as this reflects how a user would test the site locally.
